# file: docker-compose.yml

version: '3.8'

services:
  # Go 后端服务
  backend:
    build:
      context: ./backend # 指定 Dockerfile 所在的目录
    container_name: seckill-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      # 依赖的服务，会确保它们先启动
      - mysql
      - redis
      - rabbitmq
    networks:
      - seckill-net

  # Vue 前端服务 (通过 Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: seckill-frontend
    restart: always
    ports:
      - "80:80" # 将宿主机的 80 端口映射到容器的 80 端口
    depends_on:
      - backend
    networks:
      - seckill-net

  # MySQL 服务 (配置不变)
  mysql:
    image: mysql:8.0
    container_name: seckill-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: seckill_db
      MYSQL_USER: seckill_user
      MYSQL_PASSWORD: your_strong_user_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - seckill-net

  # Redis 服务 (配置不变)
  redis:
    image: redis:6.2-alpine
    container_name: seckill-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - seckill-net

  # RabbitMQ 服务 (配置不变)
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: seckill-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - seckill-net

networks:
  seckill-net:
    driver: bridge
